### ISSUE TITLE
TODO: support pppoe

### ISSUE THREAD

**Issue by olafhering** [openSUSE/wicked#17]
From TODO file:

- support pppoe

**Comment by Grunthos** [comment]
Any news on this? Having just 'upgraded' to SuSE 13.2 I am feeling rather let down.

**Comment by Grunthos** [comment]
Just checking, but getting on for 2 years and no movement?

Those of us who have bridged modems would really like a solution.

**Comment by mtomaschewski** [comment]
Yes, I know, but we have to implement what's requested via features.opensuse.org / fate.suse.com.
Does not make sense to track it multiple times -- it's requested in https://fate.suse.com/317976
