### ISSUE TITLE
TODO: route tables and improve routing support

### ISSUE THREAD

**Issue by olafhering** [openSUSE/wicked#24]
From TODO file:
- route tables and improve routing support, implement routing tables/rules rules support to configure simple multihoming.
  Note: Our productive servers (dist.suse.de) require this.

**Comment by furlongm** [comment]
If this is going to be implemented, or if it already is, would it use /etc/sysconfig/network/ifrule-${interface}  for the ip rules? I can't find any information on how to correctly add ip rules for suse.

**Comment by mtomaschewski** [comment]
Yes, ifrule-${interface} with lines like in "ip rule add $line". The feature request is https://fate.suse.com/312217 (SP1: moved to SP2 as other network stuff is more important).

**Comment by mtomaschewski** [comment]
Implemented in pull #645, version 0.6.33
