### ISSUE TITLE
TODO: dhcpv4 renew iBFT adress

### ISSUE THREAD

**Issue by olafhering** [openSUSE/wicked#36]
From TODO file:

- try to request (renew) iBFT provided address in iBFT-dhcp mode (but do newer remove it from the interface, even the dhcp server suggests other IP; add additionally instead) to not break iSCSI[, ...] devices.

**Comment by mtomaschewski** [comment]
renew is done already a long time. the addition to not remove old IP address is not needed iSCSI can handle this (acc. to last discussion about).
