### ISSUE TITLE
Martian source messages

### ISSUE THREAD

**Issue by microchip8** [openSUSE/wicked#432]
First, let me say that I'm very new to wicked and just installed it on openSUSE 13.1 from the network repo. The only thing I did is install and enable & start it. No messing with config files at all...

My PC has two NICs, enp3s0 and enp4s0. The enp3s0 is connected to the cable modem and gets its IP from the DHCP of my ISP. The enp4s0 is connected to my router and gets its IP from there, which is always 192.168.1.100.

I have noticed that every now and then (I suspect when wicked requests an IP lease) I see the below in dmesg

IPv4: martian source 94.224.17.153 from 192.168.1.2, on dev enp3s0

I do not know from where the 192.168.1.2 address comes as my router sits on 192.168.1.1. I also do not really know why it only happens on the enp3s0 interface and never on the enp4s0 one.

So my question is, is there something I need to do to get away with these messages? Maybe I did something wrong. But like I said, I did not edit anything. Just installed wicked and started it.

**Comment by mtomaschewski** [comment]
rp_filter issue --  related to network setup and reported by the kernel, has nothing to do with wicked.
