### ISSUE TITLE
IPv6 renew time

### ISSUE THREAD

**Issue by microchip8** [openSUSE/wicked#517]
Hi,

I have a router which assigns IPv6 addresses to my computers using DHCPv6 server it runs. All my computers get from wicked an IPv6 address however it does not get renewed in time and the addresses expire and disappear. How can I make wicked auto-renew in time just like it does for IPv4? Below is the DHCPv6 server config which specifically has the renew time set

interface br0 {
option dns_servers 2001:4860:4860:0000:0000:0000:0000:8888 2001:4860:4860:0000:0000:0000:0000:8844 ;
renew-time 43200 ;
rebind-time 64800 ;
prefer-life-time 86400 ;
valid-life-time 86400 ;
allow rapid-commit ;
link LAN {
pool {
range 2002:5ee0:1c27::1000 to 2002:5ee0:1c27::2000/64;
};
};
};

This is the leaseinfo IPv6 file found in /run/wicked for one of my computers

INTERFACE='enp3s0'
TYPE='dhcp'
FAMILY='ipv6'
UUID='863be754-3a74-0c00-2303-00000e000000'
IPADDR='2002:5ee0:1c27::1001/64'
PREFIXLEN='64'
ACQUIRED='1424596833'
CLIENTID='00:01:00:01:1c:59:06:c8:bc:5f:f4:c9:f3:5d'
SERVERID='00:03:00:01:e4:f4:c6:18:19:51'
SERVERADDR='fe80::be5f:f4ff:fec9:f35d'

I do not see a RENEWALTIME in that file like it is present in the IPv4 leaseinfo file or am I missing something?

**Comment by mtomaschewski** [comment]
A DHCPv6 lease does not have a renewal-/rebind-time as a DHCPv4 lease has,  but a  set of  IAs (ia-na here), with separate renewal/rebind in each IA  (see /var/lib/wicked/lease-*-dhcp-ipv6.xml,
leaseinfo is just a dump of the most important things from  the lease).

Except of this, it is a lease priority handling bug: https://bugzilla.suse.com/show_bug.cgi?id=920889
We're working on a fix.

**Comment by microchip8** [comment]
ah, thanks. I know little about DHCPv6 so I assumed it behaves like v4

**Comment by microchip8** [comment]
Hello,

I reported this issue almost 2 months ago and am still waiting for a fix. If a fix is not in the workings soon, could you at least tell me how to renew the IPv6 address manually without restarting the NIC to force wicked to get addresses?

Thanks

**Comment by pwieczorkiewicz** [comment]
On Fri, 10 Apr 2015 06:17:52 -0700
microchip8 <notifications@github.com> wrote:

> Hello,
> 
> I reported this issue almost 2 months ago and am still waiting for a
> fix. If a fix is not in the workings soon, could you at least tell me
> how to renew the IPv6 address manually without restarting the NIC to
> force wicked to get addresses?
> 
> Thanks
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/openSUSE/wicked/issues/517#issuecomment-91554461

Thanks for reporting. Please see the corresponding bug report:
https://bugzilla.opensuse.org/show_bug.cgi?id=920889

We are working on the fix.

-- 
Best Regards,
Pawel Wieczorkiewicz <pwieczorkiewicz@suse.de>, Linux System Developer

SUSE LINUX GmbH, GF: Jeff Hawn, Jennifer Guild, Felix Imendörffer, HRB
21284 (AG Nürnberg) Maxfeldstraße 5 / 90409 Nürnberg / Germany / Phone:
+49-911-740 53 - 613

**Comment by mtomaschewski** [comment]
Fixed by https://github.com/openSUSE/wicked/pull/539 and released in https://github.com/openSUSE/wicked/releases/tag/version-0.6.18
