### ISSUE TITLE
sit0 ifdown handling

### ISSUE THREAD

**Issue by pwieczorkiewicz** [openSUSE/wicked#527]
Interfaces like sit0 and tunl0 (of sit and ipip modules respectively) are not removed by the kernel on ifdown. Kernel seems to ignore the netlink call. Furthermore these interfaces are automatically created on module load.

This could be improved in order to avoid waiting until timeout at wicked client (no device-delete event arrives).

<pre>
# ip tunnel del sit0 mode sit
delete tunnel "sit0" failed: Operation not permitted
</pre>

**Comment by mtomaschewski** [comment]
it's a kernel behavior, not really anything wicked related. sit0, ... are special purpose devices.
