### ISSUE TITLE
Wicked and network boot

### ISSUE THREAD

**Issue by allspace** [openSUSE/wicked#533]
This is just one question:
Can wicked work with network boot, or root is on an network device?

In network boot case, network is generally brought up at initrd stage. After switch root, systemd will run other user space service, include network service like wicked. Will wicked be able to preserve existing network connections and avoid network broken?

The case includes static IP and DHCP. For DHCP, how does wicked reuse lease which was required in initrd?

**Comment by pwieczorkiewicz** [comment]
Yes, it can. However please note wicked has some dependencies e.g. to dbus, certain libraries like libnl3 etc. For instance in dracut there is no dbus, thus it is at the moment not possible to use wicked as is (only its dhcp supplicants). 
We do plan to add some functions to configure interfaces by client only in cases like emergency shell in dracut. That's on TODO.

In initrd cases, after mounting root fs, the lease files from /var/{lib,run}/wicked/ should be copied to root fs corresponding dirs and then reused when systemd starts network.service.

Also wicked is capable of configuring iBFT interfaces.

**Comment by allspace** [comment]
Thank you for anwser. I have no intention to use wicked in initrd. I just hope that wicked does not break existing connection which is set up in initrd.

BTW: where can I find specification about lease-eth0-dhcp-ipv4.xml. Which field is "must", and which is optional. Specially for "UUID", how can I generate UUID in initrd, and can be recognized by wicked  run on root fs.

**Comment by pwieczorkiewicz** [comment]
The easiest way would be to use wicked dhcp supplicants (/usr/lib/wicked/bin/wickedd-dhcp*) directly in initrd as dhcp client. You can do this as is done here for dracut:

https://build.opensuse.org/package/view_file/Base:System/dracut/0015-40network-replace-dhclient-with-wickedd-dhcp-supplic.patch?expand=1
and here:
https://build.opensuse.org/package/view_file/Base:System/dracut/0015-40network-replace-dhclient-with-wickedd-dhcp-supplic.patch?expand=1

Then you do not have to worry about lease file, it will be generated by the supplicants. All you need is to make sure it is carried along to root fs.

**Comment by allspace** [comment]
Thanks. But for some reason, I cannot use wickedd-dhcp* in initrd. I hope I can generate lease-eth0-dhcp-ipv4.xml in my code. Most of fields in the file are extracted from dhcp response, except "uuid", "update", "state". (I assume "acquired" is the timestamp when the lease is acquired.)

Specially how to generate uuid in initrd which can be recognized by wickedd run on root fs.
