### ISSUE TITLE
TODO: if-{up,down].d

### ISSUE THREAD

**Issue by olafhering** [openSUSE/wicked#56]
From TODO file:

if-{up,down].d
- What about all the “ifup” hooks installed by another software (e.g. samba-client with its MODIFY_SMB_CONF, xen, ...)? I don't think it makes sense to try to call as they are; it would  not work because:
  - sysconfig scripts/funcions are not available/installed,
  - different dhcp client in use, … ifup state is not available
  - perhaps they're not needed at all, e.g. samba-client hook needs to be adopted, xen too.

**Comment by mtomaschewski** [comment]
see "man ifcfg"
