### ISSUE TITLE
Default IPv6 route

### ISSUE THREAD

**Issue by microchip8** [openSUSE/wicked#570]
Hello,

I have 2 NICs on my server, both of which have IPv4 and IPv6. For IPv4, I set in /etc/sysconfig/network/ifcfg-enp1s0 the option DHCLIENT_SET_DEFAULT_ROUTE to yes and for ifcfg-enp2s0 to no. I'd like to do the same but this time for IPv6. Is there a similar variable I can set for IPv6 as the one above?

Thanks

**Comment by mtomaschewski** [comment]
No, the DHCPv6 protocol does not handle routing at all: Configure & activate router advertisements (install radvd if this is a linux box) on your router to get routing. For DHCPv6, set managed flag in the RA to on.
To disable of a default route via RA on a  device, set e.g. "net.ipv6.conf.eth0.accept_ra_defrtr = 0" in /etc/sysctl.d/somefile.conf. See also "man ifsysctl".

**Comment by SchoolGuy** [comment]
Addendum to this issue: I had the same problem as the original post author. In my case I missed additionally the fact that I need to accept the router advertisements even if forwarding for IPv6 is enabled. Below the command with the temporary fix can be viewed:

```
sysctl -w net.ipv6.conf.<interface>.accept_ra=2
```

Source: https://serverfault.com/a/1076713/408066

**Comment by cfconrad** [comment]
To make this sysctl permanent, simply put it in one of the sysctl files, see `man ifsysctl`
```bash
echo 'net.ipv6.conf.<interface>.accept_ra=2'  >> /etc/sysconfig/network/ifsysctl
```
