### ISSUE TITLE
TUNNEL_KEY and  TUNNEL_CSUM options in ifcfg-tunnel

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/wicked#619]
Hello! There're some questions about ifcfg-tunnel.

http://man7.org/linux/man-pages/man8/ip-tunnel.8.html 
```
key K

              ikey K

              okey K ( only GRE tunnels ) use keyed GRE with key K. K is
                     either a number or an IP address-like dotted quad.  The
                     key parameter sets the key to use in both directions.
                     The ikey and okey parameters set different keys for
                     input and output.
```

and
```
csum, icsum, ocsum
                     ( only GRE tunnels ) generate/require checksums for
                     tunneled packets.  The ocsum flag calculates checksums
                     for outgoing packets.  The icsum flag requires that all
                     input packets have the correct checksum. The csum flag
                     is equivalent to the combination icsum ocsum.
```

There's no info in ```man 5 ifcfg-tunnel``` in openSUSE 13.2 about these features. Are they implemented in wicked framework or are they planning to be implemented? Thank you!

**Comment by mtomaschewski** [comment]
No, they're not implemented not yet.

**Comment by MikhailKasimov** [comment]
ok, let's conside it as feature request.

**Comment by mtomaschewski** [comment]
I'd say, it fits thematically into https://fate.novell.com/317977 -- don't know if you have access to it, it's a SLES-12-SP2 feature request to permit to bind tunnels to devices (IFLA_GRE_LINK & co) and consider the dependencies in wicked. Makes sense to add all attributes.

**Comment by MikhailKasimov** [comment]
Seems, I have access to fate.opensuse.org only. But ok, as I understand, this FR is duplication a little bit of 317977 in fate.novell.org. No problem.

**Comment by mtomaschewski** [comment]
In https://github.com/openSUSE/wicked/pull/642. See ifcfg-tunnel(5).

There are also encap options, but the write part is disabled for now. Have to test it on a more recent kernel first.

**Comment by mtomaschewski** [comment]
OK, IMO it is done so far in 0.6.32.

BTW: openSUSE features can be requested as usually via https://features.opensuse.org/;
only SLES needs a request in https://fate.suse.com/ (alias https://fate.novell.com).
