### ISSUE TITLE
DHCLIENT_PRIMARY_DEVICE not supported?

### ISSUE THREAD

**Issue by dmacvicar** [openSUSE/wicked#626]
I was using `DHCLIENT_SET_DEFAULT_ROUTE` in a Vagrant configuration set to `yes` and `no` respectively in two different interfaces to make sure Vagrant did not set the route of the management interface (eth0).

Then I discovered there is a `DHCLIENT_PRIMARY_DEVICE` setting which tells the network stack that the interface is allowed to change the hostname/default route from dhcp, however, this setting does not seem to be honoured by wicked, and I can't find a match in the sources either.

**Comment by mtomaschewski** [comment]
No, this stuff was IMO almost always wrong configured and never worked properly, so we didn't
even considered to implement such thing. Simply configure correctly as needed and set
DHCLIENT_SET_DEFAULT_ROUTE=no in dhcp +  DHCLIENT_SET_DEFAULT_ROUTE=yes in
the ifcfg where you want to permit setting it to avoid "first interface wins".
Or use  DHCLIENT_ROUTE_PRIORITY instead.

DHCLIENT_SET_HOSTNAME's default was & is "no" and should be set in ifcfg to yes if needed.
Better is to make it the right way and set the machine hostname in /etc/hostname. To assume,
that there  is only 1 IP and it resolves to the hostname it more a corner case than a rule.
