### ISSUE TITLE
Please show DHCP server

### ISSUE THREAD

**Issue by dmantione** [openSUSE/wicked#663]
Hello,

A small feature request. I got into a situation were was granted IP addresses by a rogue DHCP server on my network, my computer runs OpenSuSE 42.2 alpha and thus wicked. I found it surprisingly hard to query the ip/mac address of the DHCP server from wicked: I could neither retrieve it with "journalctl" nor with "wicked ifstatus".

Would it be possible to modify "wicked ifstatus" to show the DHCP server that granted your address. Basically you now see:

daniel:~ # wicked ifstatus eth0 
eth0            up
      link:     #2, state up, mtu 1500
      type:     ethernet, hwaddr 40:8d:5c:b1:80:90
      config:   compat:suse:/etc/sysconfig/network/ifcfg-eth0
      leases:   ipv4 dhcp granted
      leases:   ipv6 dhcp requesting
      addr:     ipv4 10.1.181.157/16 [dhcp]
      route:    ipv4 default via 10.1.199.6

I would like to see:

daniel:~ # wicked ifstatus eth0 
eth0            up
      link:     #2, state up, mtu 1500
      type:     ethernet, hwaddr 40:8d:5c:b1:80:90
      config:   compat:suse:/etc/sysconfig/network/ifcfg-eth0
      leases:   ipv4 dhcp granted from 1.2.3.4 (00:11:22:33:44:55)
      leases:   ipv6 dhcp requesting
      addr:     ipv4 10.1.181.157/16 [dhcp]
      route:    ipv4 default via 10.1.199.6

Best regards,

Daniël Mantione

**Comment by nirmoy** [comment]
try wicked  test dhcp4 <interface>
it should able to show the IP address but not the mac address.

**Comment by mtomaschewski** [comment]
We capture udp packets only, not IP or the underlying device specific data packet. It would be possible  to change to capture the whole ethernet packet + parse it manually, but conditionally on ethernet only as
on infiniband and other interface types, the sender mac address is not passed/visible at all.

**Comment by mtomaschewski** [comment]
You can use "tcpdump -Uenvfi eth0 udp port 67 or port 68" to see the mac.

**Comment by dmantione** [comment]
Having the ip address of the DHCP server is already a major help, but I believe it is is possible to retrieve the mac address assiociated with an UDP connection without too much tricks using an ARP ioctl. Something like:

#include <net/if_arp.h>

struct arpreq req;
int s; /* s is the UDP socket to query the mac address from */

strcpy(req.arp_dev, "eth0");
ioctl(s, SIOCGARP, (caddr_t)&req)

/*
  req.arp_ha should now contain the mac address
*/

ARP works with infiniband.This looks a clean solution to me, because any possible network technology will implement the ARP calls if it is relevant to that technology.

**Comment by mtomaschewski** [comment]
OK, going to clenaup my prototype... the ioctl call is not needed.

**Comment by mtomaschewski** [comment]
Could you test pull https://github.com/openSUSE/wicked/pull/679 please?

Test RPMs will build soon automatically into the repositories under:
 http://download.opensuse.org/repositories/network:/wicked:/testing/

**Comment by mtomaschewski** [comment]
> ARP works with infiniband.[...]

When I remember correctly, ioctl API's don't work, because the ib hw-address is too long (20 bytes).
This would need a netlink lookup instead. Further, it would  say who has the IP mentioned in dhcp
package in the cache, but not who were the sender :-) For now, I'll omit attempts to figure it out.

**Comment by mtomaschewski** [comment]
A pull request to update the ignore-server/prefer-server in wicked-config.5 man page would be
very appreciated... `<prefer-server mac="00:1b:21:bf:79:f0" weight="never"/>`

**Comment by mtomaschewski** [comment]
in master now
