### ISSUE TITLE
Little typo in /etc/wicked/nanny.xml

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/wicked#666]
Hello!

openSUSE 42.1: ```/etc/wicked/nanny.xml``` -- Nanny-specific (wickedd-nanny binanry) configuration.

binanry --> binary.

**Comment by mtomaschewski** [comment]
Thanks! We'll add it to our TODO for next week.

**Comment by mtomaschewski** [comment]
fixed in pull request #667
