### ISSUE TITLE
wicked prefers to nitpick dhcpd configuration over configuring your network interface

### ISSUE THREAD

**Issue by hramrach** [openSUSE/wicked#671]
Hello,

I get no IPv4 address in SUSE installer and I get these messages that show wickedd is the culprit.

2016-09-27T09:29:35.650626+00:00 wickedd-dhcp4[388]: Error: option 47 has zero length
2016-09-27T09:29:35.650654+00:00 wickedd-dhcp4[388]: Error: unable to parse DHCP4 response

This is wrong on multiple levels.

On the option-specific level option 47 is NetBIOS scope which can be empty. So setting this to empty means there is no NetBIOS scope and should there be a default scope configured in the client in case the server does not provide one it should be cleared.

Also since most (if not all) installations of OpenSUSE do not implement NetBIOS this option being wrong should no preclude non-NetBIOS networking on IPv4 to occur. This also violates the reccommendation of RFCs to be lenient in what you accept and strict in what you send in order to promote interoperability.

Finally wickedd-dhcp4 is for obtaining an IPv4 address, not for nitpicking your dhcpd configuration. I could probably come up with a bandaid for this particular option but the overall policy is wrong here. So long as enough options are present for setting up IPv4 networking it should be set up.

**Comment by mtomaschewski** [comment]
Hi!

First of all, the pull https://github.com/openSUSE/wicked/pull/678, should fix it to not nitpick.

> On the option-specific level option 47 is NetBIOS scope which can be empty.

No, the dhcp RFC defines it as minimum length 1. NetBIOS scope can be empty in NetBIOS (=default scope), but this is unrelated.

> this option being wrong should no preclude non-NetBIOS networking on IPv4 to occur.

That's true.

> This also violates the reccommendation of RFCs to be lenient in what you accept and strict in what you send in order to promote interoperability.

And the dhcp sever violates the recommendation to be strict in what you (permit to) send.

**Comment by mtomaschewski** [comment]
Test RPMs will build soon automatically into the repositories under:
  http://download.opensuse.org/repositories/network:/wicked:/testing/

**Comment by mtomaschewski** [comment]
in master now
