### ISSUE TITLE
Wicked on boot eth0 and wlan0 priority eth0 fails

### ISSUE THREAD

**Issue by dpatino82** [openSUSE/wicked#683]
My work/test environment uses two different gateways for wired and wireless networks but the same DNS.

I've already configured my wireless and wired interfaces properly. During boot, with network cable plugged my RPI3 gets 2 different IP addresses (maybe around as expected) but both of them active and so the DNS resolution seems wrong because I can't access to the RPi3 using (ssh) it's hostname neither in wired nor in wireless networks. Thus, if I use directly IP address to connect via ssh only wired IP (eth0) works properly.

I've configured ifcfg-wlan0 with: DHCLIENT_ROUTE_PRIORITY='10' and ifcfg-eth0 with DHCLIENT_ROUTE_PRIORITY='1'

The main goal is to use only the wired interface (set as higher priority), in case both interfaces were available on boot, use only eth0 and get an IP and associate it's hostname in DNS just once.

Is this possible?
Thanks,

**Comment by mtomaschewski** [comment]
This issue is IMO same to issue #684. A routing priority alone will not do what you're trying to achieve.

An ```echo 'net.ipv4.conf.all.rp_filter = 0' > /etc/sysctl.d/50-rp_filter.conf``` should relax your problems.
