### ISSUE TITLE
To extend arp command fuctionality

### ISSUE THREAD

**Issue by MikhailKasimov** [openSUSE/wicked#691]
Hello!

The ```arp [options] <ifname> <IP>``` string from ```wicked --help``` hints the idea to extend ``` wicked arp``` command to have the similar logic due to ```arp``` command.

1) ```wicked arp --cache-list <ifname>|all``` (analog to ```arp -a```: display (all) hosts in alternative (BSD) style).

2) ```wicked arp --delete <IP>|all``` (analog to ```arp -d|--delete```: delete a specified entry, will delete LLADDR parameter from ```/etc/sysconfig/network/ifcfg-<ifname>```).

3) ```wicked arp --set <IP> <LLADDR>``` (analog to ```arp -s|--set```: set a new ARP entry, will add ```LLADDR``` parameter to ```/etc/sysconfig/network/ifcfg-<ifname>``` or will replace, if ```LLADDR``` parameter is already exist in  ```/etc/sysconfig/network/ifcfg-<ifname>```).

Thanks!

**Comment by mtomaschewski** [comment]
See issue #690 -- we've added them for internal use "keeping door open" to extend when needed,
but there is no plan to do anything / extend to provide full functionality, because there are enough
utilities doing it, see also "man ip-neighbour", which handles both, ipv4 + ipv6.
