### ISSUE TITLE
macvlan does not get dhcp4 address

### ISSUE THREAD

**Issue by quicktrick** [openSUSE/wicked#756]
Hello!  I'm trying to configure `macvlan` interface on an openSUSE Tumbleweed server. It gets ipv6 address but it does not get ipv4 from my dhcp-server (isc-dhcpd on my FreeBSD router). My config is:

ifcfg-macvlan0

    STARTMODE='auto'
    BOOTPROTO=’dhcp’
    MACVLAN_DEVICE='ens1'
    MACVLAN_MODE='bridge'
    LLADDR=82:91:3e:36:83:02

After `ifup macvlan0`

    # ip a
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host
           valid_lft forever preferred_lft forever
    2: ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 30:f7:d7:03:5a:00 brd ff:ff:ff:ff:ff:ff
        inet 192.168.2.103/24 brd 192.168.2.255 scope global ens1
           valid_lft forever preferred_lft forever
        inet6 fe80::32f7:d7ff:fe03:5a00/64 scope link
           valid_lft forever preferred_lft forever
    3: wlp1s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
        link/ether e4:02:9b:e0:16:e5 brd ff:ff:ff:ff:ff:ff
    4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
        link/ether 02:42:84:73:da:d3 brd ff:ff:ff:ff:ff:ff
        inet 172.17.0.1/16 scope global docker0
           valid_lft forever preferred_lft forever
    8: macvlan0@ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
        link/ether 82:91:3e:36:83:02 brd ff:ff:ff:ff:ff:ff
        inet6 fe80::8091:3eff:fe36:8302/64 scope link
           valid_lft forever preferred_lft forever

Though a test seems to be good:

    # wicked test dhcp4 macvlan0
    wicked: macvlan0: Request to acquire DHCPv4 lease with UUID 2482225b-1552-0d00-6835-000001000000
    INTERFACE='macvlan0'
    TYPE='dhcp'
    FAMILY='ipv4'
    UUID='2482225b-1552-0d00-6835-000001000000'
    IPADDR='192.168.2.104/24'
    NETMASK='255.255.255.0'
    NETWORK='192.168.2.0'
    PREFIXLEN='24'
    GATEWAYS='192.168.2.1'
    DNSDOMAIN='mydomain.tld'
    DNSSERVERS='192.168.2.1'
    DNSSEARCH='mydomain.tld'
    CLIENTID='ff:3e:36:83:02:00:01:00:01:21:21:90:a8:30:f7:d7:03:5a:00'
    SERVERID='192.168.2.1'
    SENDERHWADDR='00:e0:4c:64:97:d2'
    ACQUIRED='1528988198'
    LEASETIME='7200'

It does not get ipv4 address even after reboot.  Am I doing anything wrong?

From syslog:

    + journalctl -u wicked -S-2h -Unow --no-pager
    -- Logs begin at Sat 2017-08-12 13:10:27 MSK, end at Thu 2018-06-14 19:30:59 MSK. --
    Jun 14 17:53:12 vorke systemd[1]: Stopping wicked managed network interfaces...
    Jun 14 17:53:14 vorke wicked[12903]: ens1            device-ready
    Jun 14 17:53:14 vorke systemd[1]: Stopped wicked managed network interfaces.
    Jun 14 17:53:14 vorke systemd[1]: Starting wicked managed network interfaces...
    Jun 14 17:53:20 vorke wicked[13205]: lo              up
    Jun 14 17:53:20 vorke wicked[13205]: ens1            up
    Jun 14 17:53:20 vorke wicked[13205]: macvlan0        up
    Jun 14 17:53:20 vorke systemd[1]: Started wicked managed network interfaces.
    Jun 14 18:03:16 vorke systemd[1]: Stopping wicked managed network interfaces...
    Jun 14 18:03:17 vorke wicked[13756]: ens1            device-ready
    Jun 14 18:03:17 vorke systemd[1]: Stopped wicked managed network interfaces.
    -- Reboot --
    Jun 14 18:03:43 vorke systemd[1]: Starting wicked managed network interfaces...
    Jun 14 18:03:49 vorke wicked[1167]: lo              up
    Jun 14 18:03:49 vorke wicked[1167]: ens1            up
    Jun 14 18:03:49 vorke wicked[1167]: macvlan0        up
    Jun 14 18:03:49 vorke systemd[1]: Started wicked managed network interfaces.

From `dhcpd.log` on FreeBSD router:

    Jun 14 17:56:37 alib dhcpd: DHCPDISCOVER from 82:91:3e:36:83:02 via igb2
    Jun 14 17:56:38 alib dhcpd: DHCPOFFER on 192.168.2.104 to 82:91:3e:36:83:02 via igb2

From `dhcpd.leases` on FreeBSD router (time here is in UTC, i.e. -3 hours from the previous logs'):

    lease 192.168.2.104 {
      starts 4 2018/06/14 14:56:37;
      ends 4 2018/06/14 14:58:37;
      cltt 4 2018/06/14 14:56:37;
      binding state free;
      hardware ethernet 82:91:3e:36:83:02;
      uid "\377>6\203\002\000\001\000\001!!\220\2500\367\327\003Z\000";
    }

However, on openSUSE Tumbleweed:

    # ifdown macvlan0
    # ifup macvlan0
    macvlan0        up
    # ip a show dev macvlan0
    7: macvlan0@ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
        link/ether 82:91:3e:36:83:02 brd ff:ff:ff:ff:ff:ff
        inet6 fe80::8091:3eff:fe36:8302/64 scope link
           valid_lft forever preferred_lft forever

Changing `MACVLAN_MODE='bridge'` to the default one (`'vepa'`) does not help.

**Comment by quicktrick** [comment]
If I set a static IP on that server, everything seems to be working:

    # ip address add 192.168.2.91/24 dev macvlan0

    # ip address show dev macvlan0
    4: macvlan0@ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
        link/ether 82:91:3e:36:83:02 brd ff:ff:ff:ff:ff:ff
        inet 192.168.2.91/24 scope global macvlan0
           valid_lft forever preferred_lft forever
        inet6 fe80::8091:3eff:fe36:8302/64 scope link
           valid_lft forever preferred_lft forever
    
    # ping 192.168.2.91
    PING 192.168.2.91 (192.168.2.91) 56(84) bytes of data.
    64 bytes from 192.168.2.91: icmp_seq=1 ttl=64 time=0.092 ms
    64 bytes from 192.168.2.91: icmp_seq=2 ttl=64 time=0.181 ms

And the same from the outside (from my FreeBSD router):

    # ping 192.168.2.91
    PING 192.168.2.91 (192.168.2.91) 56(84) bytes of data.
    64 bytes from 192.168.2.91: icmp_seq=1 ttl=64 time=0.092 ms

What's wrong with it when using dhcp?

**Comment by mtomaschewski** [comment]
> BOOTPROTO=’dhcp’

The variable is using wrong quote character. The error about is printed as debug :-/
See ```wicked --debug all show-config >/dev/null``` output:

```wicked: ifcfg-macvlan1: Unknown BOOTPROTO="’dhcp’" value "’dhcp’"```

Use BOOTPROTO='dhcp' or BOOTPROTO="dhcp" or BOOTPROTO=dhcp and then it works.

**Comment by quicktrick** [comment]
Thanks a lot @mtomaschewski !  I can't check my old config, because I've been using static IP for that interface since that time (I even moved to `ipvlan` instead of `macvlan` for some reasons). Thanks anyway for your kind attention and your reply!
