### ISSUE TITLE
Wrong wpa_supplicant configuration is generated in case of MSCHAPv2

### ISSUE THREAD

**Issue by kbabioch** [openSUSE/wicked#777]
As diagnosed in [bnc#1026807](https://bugzilla.suse.com/show_bug.cgi?id=1026807), a change to wpa_supplicant in commit [f24e48861d50b6b6fc5681f75d4aa75144862853](https://w1.fi/cgit/hostap/commit/?id=f24e48861d50b6b6fc5681f75d4aa75144862853) has been made, which changed the behavior in regards to `auth=` and `autheap=`.

The commit message reads:

>This patch fixes an issue with an invalid phase2 parameter value auth=MSCHAPv2 getting interpreted >as auth=MSCHAP (v1) which could degrade security (though, only within a protected TLS tunnel). >Now when invalid or unsupported auth= phase2 parameter combinations are specified, EAP-TTLS >initialization throws an error instead of silently doing something.

The configuration files generated by wicked are affected by this, since they set `WIRELESS_EAP_AUTH='MSCHAPv2'`, which will no longer work, resulting in issues (see bug mentioned previously).

**Comment by kbabioch** [comment]
After having a look at the code, this is actually a little bit more complicated. `WIRELESS_EAP_AUTH='MSCHAPv2'` is only setting the internal representation, and is only loosely related to what is effectively passed to `wpa_supplicant`. In the original bug report the error is

> TLS: Unsupported Phase2 EAP method 'mschapv2'

As you can see `mschapv2` is passed to `wpa_supplicant`, not `MSCHAPv2`. However both are invalid, as `MSCHAPv2` needs to be passed to `wpa_supplicant`.

Not sure what the best approach to fix this would be. We definitely need to fix the interface towards `wpa_supplicant`, but we could be more relaxed when parsing the configuration files. Or we should just pass this along as directly as possible as not modify these strings at all.

**Comment by kbabioch** [comment]
The problem is related to an array, which is used to transform strings to the internal representation of the type:

https://github.com/openSUSE/wicked/blob/e6e00395dfe3c6b789dd8ab22088e76ad9d99f6d/src/wireless.c#L596-L621

Not sure what the best approach to fix this, would be. I can come up with something, but I'm not sure about all of the consequences. Unfortunately there seem to be no continuous integration, so I would prefer if someone with more experience with this codebase, would change the code in the best possible way.

By the way: There are many more and similar definitions for key management, which are probably also not working correctly and/or rely on lenient parsing on `wpa_supplicant` side of things. At least it is written in uppercase letters in the man page and/or example configuration files.

These (among others) might be problematic:

https://github.com/openSUSE/wicked/blob/e6e00395dfe3c6b789dd8ab22088e76ad9d99f6d/src/wireless.c#L581-L588

https://github.com/openSUSE/wicked/blob/e6e00395dfe3c6b789dd8ab22088e76ad9d99f6d/src/wireless.c#L556-L565

https://github.com/openSUSE/wicked/blob/e6e00395dfe3c6b789dd8ab22088e76ad9d99f6d/src/wireless.c#L535-L540

https://github.com/openSUSE/wicked/blob/e6e00395dfe3c6b789dd8ab22088e76ad9d99f6d/src/wireless.c#L513-L519

**Comment by mtomaschewski** [comment]
Fix in https://github.com/openSUSE/wicked/pull/780 to use the correct **wpa** table not the xml schema table. Further, additional change to assume mschapv2 for PEAP by default (PEAPv0) -- yast2 can set it,
but it is required on a detail page.

**Comment by kbabioch** [comment]
Since this has been addressed with #780, let's close this issue.
