### ISSUE TITLE
Support four nameservers

### ISSUE THREAD

**Issue by nekoswag** [openSUSE/wicked#779]
At the moment the yast2 dialog for wicked can configure three nameservers at a time. Could that be extended to support four servers? Then you could configure both IPv4 and IPv6 DNS with a fallback server each.

**Comment by nirmoy** [comment]
Three nameservers is limit from libc resolver. So its not possible to extend from yast2 side. It's possible to use DNS cache(dnsmasq...) to have more then 3 nameservers.
