### ISSUE TITLE
wicked-config man page about nanny default needs to be updated.

### ISSUE THREAD

**Issue by m0rbo** [openSUSE/wicked#815]
https://github.com/openSUSE/wicked/blob/master/man/wicked-config.5.in
states: "The default value is \fBfalse\fP."

When, in reality, the default value is "true". 
This was changed in fate#318977
https://fate.suse.com/318977
And:
https://github.com/openSUSE/wicked/pull/543

**Comment by mtomaschewski** [comment]
Yes, thanks!
We have also to remove this finite state machine test mode hybrid (use-nanny false).
