### ISSUE TITLE
wickedd and openvswitch should not start in parallel

### ISSUE THREAD

**Issue by stefannica** [openSUSE/wicked#822]
According to the official documentation [1], the OVS services need
to start long before the network (wicked) service, to be able to
interact with the service during boot. However, both OVS and wicked
are multi-service applications and the way that OVS and wicked systemd
service files are being set up, using a `Before=network.service` entry
in the OVS systemd unit file is not enough to guarantee that OVS
services are fully started before wicked services start.

Starting OVS and wicked in parallel can indeed cause problems
that are not easily reproducible, such as this:

```
Jan 22 23:35:12 dfa-16-3e-d2-b0-42 systemd[1]: Starting Open vSwitch...
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Starting wicked network management service daemon...
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 kernel: openvswitch: Open vSwitch switching datapath
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Started wicked network management service daemon.
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Starting wicked network nanny service...
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 kernel: device br-fixed entered promiscuous mode
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd-udevd[981]: Could not generate persistent MAC address for br-fixed: No such file or directory
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 ovs-ctl[797]: Starting ovs-vswitchd..done
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Started Open vSwitch.
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Started wicked network nanny service.
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 systemd[1]: Starting wicked managed network interfaces...
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 wickedd-nanny[947]: device br-public: failed to bind services and methods for waitDeviceReady()
Jan 22 23:35:13 dfa-16-3e-d2-b0-42 wickedd-nanny[947]: device br-fixed: failed to bind services and methods for waitDeviceReady()
```

This can easily be alleviated by customizing the OVS or wicked systemd service unit
configuration files, but I still think the official product should cover this somehow, either
by updating the documentation to say that the `Before=network.service` approach
is no longer valid, or by changing the way the wicked.service unit is synchronized
with the other service units to make that statement true again.

[1] https://en.opensuse.org/Portal:Wicked/OpenvSwitch

**Comment by JanZerebecki** [comment]
If this isn't fixed in wicked so it is tolerant against either ordering, instead of documenting it, just changing the package would be better. That is to either declare After OVS in wickedd.service or declare Before wickedd.service in OVS. This worked according to tests Stefan did.

**Comment by rtorrero** [comment]
@stefannica @JanZerebecki sorry for the delay, somehow missed the notification.

Shouldn't ovs use `Before=network-pre.service` instead? If this works it would be a cleaner way of synchronization (without mentioning any specific unit in neither of the service files)

See -> https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

If this doesn't work, let us know so we can further discuss a solution.

**Comment by rtorrero** [comment]
I see it's actually using it but in the `After` section, so there is probably a good reason for that.

**Comment by rtorrero** [comment]
@JanZerebecki I just read that on the mentioned issue that network-pre.target is not an option. In that case, since wicked already provides a way of maintaining ovs bridges though it's configuration, I'd see no problem in adding a openvswitch to our After=
