### ISSUE TITLE
dhcp + static route works inconsistently

### ISSUE THREAD

**Issue by matwey** [openSUSE/wicked#833]
Hello,

I am running wicked from `master` with the following `compat` configuartion:

`ifcfg-veth1`:
```
STARTMODE=auto
BOOTPROTO=dhcp
ZONE=public
```

`ifroute-veth1`:
```
192.168.100.1 - - veth1
```

After the first network configuration, the route table looks like the following:
```
default via 10.0.0.1 dev veth1 proto dhcp 
10.0.0.0/24 dev veth1 proto kernel scope link src 10.0.0.180 
192.168.100.1 dev veth1 scope link
```

However, if DHCP server forces the client to use another lease (for instance due to updated network configuration), the static route is missed:
```
default via 192.168.22.1 dev veth1 proto dhcp 
192.168.22.0/24 dev veth1 proto kernel scope link src 192.168.22.14 
```

**Comment by mtomaschewski** [comment]
This should not happen -- dhcp shouldn't be able to change any static routes. We beed to investigate and test it. Adding this issue to my TODO list.

**Comment by mtomaschewski** [comment]
I've looked wrong here and it is not a bug, but invalid issue / permitted configuration. The configured static route is a **direct** route is valid and **can** be applied to the interface (it does not have a gateway and thus e.g. `IPADDR=` dependencies where the the gateway needs prepended a direct route).
