### ISSUE TITLE
Set a metric to the default route for seamless failover

### ISSUE THREAD

**Issue by breezerider** [openSUSE/wicked#842]
As I ran into the issue with wired-to-wireless-failover (see #684), I found a potential workaround. One can have both WiFi and Ethernet up at the same time and respective routes set up with different metrics that allows for a seamless transition. However, it does not quite work yet as by default wicked does not set the metric for the default route and there seems to be no way to do so. Is it possible to introduce an option for this?

**Comment by mtomaschewski** [comment]
See `man 5 ifcfg-dhcp`:
```
       DHCLIENT_ROUTE_PRIORITY
              This option allows to set a metric/priority for DHCPv4 routes. Default is 0.
```
-> Add `DHCLIENT_ROUTE_PRIORITY=100` to ifcfg-wlan0.

**Comment by breezerider** [comment]
Thank you for the suggestion. I tried this option and now only the default route is assigned a metric, but not any other routes obtained via DHCP:

`$ ip route show
default via 192.168.1.1 dev enp0s25 proto dhcp metric 100 
default via 192.168.1.1 dev wlp3s0 proto dhcp metric 500 
192.168.1.0/24 dev enp0s25 proto kernel scope link src 192.168.1.169 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.238 `

Is this expected? For instance, would not it lead to routing problems if `wlp3s0` is activated before `enp0s25`?

**Comment by breezerider** [comment]
> See `man 5 ifcfg-dhcp`:
> 
> ```
>        DHCLIENT_ROUTE_PRIORITY
>               This option allows to set a metric/priority for DHCPv4 routes. Default is 0.
> ```
> 
> -> Add `DHCLIENT_ROUTE_PRIORITY=100` to ifcfg-wlan0.

Thank you for the suggestion. I tried this option and now only the default route is assigned a metric, but not any other routes obtained via DHCP:

```
$ ip route show
default via 192.168.1.1 dev enp0s25 proto dhcp metric 100 
default via 192.168.1.1 dev wlp3s0 proto dhcp metric 500 
192.168.1.0/24 dev enp0s25 proto kernel scope link src 192.168.1.169 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.238 
```

Is this expected? For instance, would not it lead to routing problems if `wlp3s0` is activated before `enp0s25`?
