### ISSUE TITLE
wicked dracut integration (bo#1182227)

### ISSUE THREAD

**Issue by anthr76** [openSUSE/wicked#868]
Hello,

Posting this here as an official github issue for [bo#1182227](https://bugzilla.opensuse.org/show_bug.cgi?id=1182227). Has there been any updates to this issue?

**Comment by mtomaschewski** [comment]
I guess, it's as commented in https://bugzilla.opensuse.org/show_bug.cgi?id=1182227#c9. I'm closing this issue in order to keep thing in one place.
