### ISSUE TITLE
RFC 8106 (RDNSS & DNSSL through Router Advertisement) support

### ISSUE THREAD

**Issue by disich** [openSUSE/wicked#889]
wicked does not seem to support RFC 8106 (RDNSS & DNSSL through Router Advertisement) . Seems some work has been done with respect to this in the past (commit 6327d2b9e and de9409f47 by @mtomaschewski) but it is not complete.

**Comment by mtomaschewski** [comment]
It receives them as forwarded by the kernel via netlink events and applying then as auto6 lease when they arrive,
but does not explicitly waits for them, except BOOTPROTO=auto6 or BOOTPROTO=dhcp+auto6 is set, where
wicked explicitly requests an RA (sends RS). When it does not work, we need details: debug logs incl. icmpv6
tcpdump and rtnetlink (nlmon) captures -- please open a bug report, see http://bugs.opensuse.org and also
https://en.opensuse.org/openSUSE:Bugreport_wicked.

Please ensure `net.ipv6.conf.<ifname>.autoconf = 1` and `net.ipv6.conf.<ifname>.accept_ra = 1` are configured
(in /etc/sysctl.d/... or /run/sysctl.d/... files). As `net.ipv6.conf.default.forwarding = 1` (=router) disables autoconf,
it's needed to set accept_ra to **2**, see https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt.
