### ISSUE TITLE
ignoring obsolete <use-nanny>false</use-nanny> option, please remove

### ISSUE THREAD

**Issue by MarioBlunk** [openSUSE/wicked#890]
I'm trying to disable nanny via the file /etc/wicked/local.xml:

It reads:

`<config>
	<use-nanny>false</use-nanny>
</config>
`

command: "rcwicked status" says: 
`ignoring obsolete <use-nanny>false</use-nanny> option, please remove`

The wicked version is 0.6.67.

What am I doing wrong ?

**Comment by cfconrad** [comment]
Using wicked without nanny is obsolete and was removed in https://github.com/openSUSE/wicked/pull/851. This PR was added in wicked version `0.6.65`.

**Comment by mtomaschewski** [comment]
It is in /etc/wicked/local.xml or a user modified /etc/wicked/common.xml (like in https://github.com/openSUSE/wicked/pull/851/files#diff-e7906ea8dd42ce4f7b7f71c2ffab8dd7614989a47942c7149f7bc6b5439cd502L23)

**Comment by MarioBlunk** [comment]
Please be patient with me. From the documentation I learned that nanny is responsible for auto-configuration of network interfaces. In my case I have a laptop PC with an internal network interface ens5 and a PCMCIA network card eth0. Both cards are statically configurated with IPv4 addresses. But from time to time, completely randomly, with or without network cables attached, wicked comes up with eth0 completely forgotten and an unconfigurated eth1 instead.  So I assumed, disabling nanny would solve the problem.
 I will provide you with all necessary debug information if your time allows to debug the issue further. 
Thank you in advance.

**Comment by cfconrad** [comment]
For me it sounds like udev. Do you have a udev-rule which ensure the name of that network card, something like:
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="<your mac-addr here>", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
```
Take a look into `/etc/udev/rules.d/70-persistent-net.rules` this would be the first place I would start.
To find the correct attributes see: `udevadm info -q all -a /sys/class/net/eth[01]`

**Comment by MarioBlunk** [comment]
I'm sorry for the delay. Now I found the time to test your proposal. Thanks for the hint with the udev file. It seems to work for now. After a lot of testing the problem seems to be solved. The hint on the udev file should find a place in your official documentation so that other users do not run into the same struggle.
Thank you again and have a great day.
