### ISSUE TITLE
For openSUSE 15.3 wicked show wlan0 no-device

### ISSUE THREAD

**Issue by fred214** [openSUSE/wicked#902]
In openSUSE 15.2 the wicked works well with Intel AC 9260, but when I update to 15.3 it's not working:
```
sudo lspci -k
Network controller: Intel Corporation Wireless-AC 9260 (rev 29)
Subsystem: Intel Corporation Device 0041
Kernel driver in use: iwlwifi
Kernel modules: iwlwifi

sudo wicked ifup all
lo     up
wlan0  no-device
```

**Comment by fred214** [comment]
My host doesn't install iw tools and the hosts can not access the network now, but for `ls /sys/class/net/` there is no wlan0 in the result
```
sudo ls /sys/class/net/
br-ffda0f00b153 docker0 eth0 lo veth3c402a2 veth5428f0 veth56c6c07 veth70f71d1 veth7dbeedc
```

**Comment by cfconrad** [comment]
ok, so `sysfs` show you do not have `wlan0`. With other words, the output of wicked is correct.
What system you are using?
```bash
cat /etc/os-release
```

I would say you need to install the `iw` utils simply with 
```bash
sudo zypper in iw
```
and then plz run `sudo iw phy` again.

**Comment by mtomaschewski** [comment]
As https://github.com/openSUSE/wicked/issues/902#issuecomment-1068698274 shows,  it's not a wicked but a kernel driver issue.
