### ISSUE TITLE
wireless-tools / libiw is dead, please replace with libnl3

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/wicked#910]
With Fedora Linux 36, `wireless-tools` has been dropped due to lack of upstream support and being superseded by Linux kernel native UAPIs for over a decade. These APIs are generally available from the `libnl3` library, which Wicked already depends on.

However, Wicked still depends on `wireless.h` from `wireless-tools-devel` (`libiw-devel` in openSUSE). Please migrate to `libnl3` for these remaining cases.

Information for `libnl3` is at: http://www.infradead.org/~tgr/libnl/

Reference: https://fedoraproject.org/wiki/Changes/RemoveWirelessExtensions

**Comment by cfconrad** [comment]
release 0.6.70 should get it
