### ISSUE TITLE
wicked and systemd: when network is really online?

### ISSUE THREAD

**Issue by svalx** [openSUSE/wicked#921]
I use openSUSE 15.4 with wicked as network manager, and need to Dante socks server on this host. sockd.service contain After=network.target condition, but Dante can't bind to network interface at system start because slow dhcp server give a lease only after 2 minutes. I changed condition to After=network-online.target but no success - it reached after 90 seconds timeout, according https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/, but no IP on eht0 at that time.
And now a question: how do I make sure that my service starts after the network is really online when wicked using? For this purpose NetworkManager have a NetworkManager-wait-online.service, systemd-networkd have a systemd-networkd-wait-online.service. What about wicked?
I found temporary solution by using timer for start sockd.service after 2 minutes, but this is just a duct tape and not suitable for production...

**Comment by cfconrad** [comment]
you could try the `WAIT_FOR_INTERFACES` option in `/etc/sysconfig/network/config` (see: `man ifcfg`).
